
 var wolfMoves = [
    { 
      "Moves": "Jab 1",
      "Startup": 4,
      "TotalFrames": "21",
      "Landing Lag": "na",
      "Notes": "Transitions to jab 2 as early as frame 7",
      "BaseDamage": "2.0",
      "Shieldlag": "7",
      "Shieldstun": "3",
      "<-Which hitbox?": "",
      "Advantage": "-14"
    },
    {
      "Moves": "Jab 2",
      "Startup": "4",
      "TotalFrames": "21",
      "Landing Lag": "na",
      "Notes": "Transitions to jab 3 as early as frame 7",
      "BaseDamage": "2.0",
      "Shieldlag": "5",
      "Shieldstun": "3",
      "<-Which hitbox?": "",
      "Advantage": "-17"
    },
    {
      "Moves": "Jab 3",
      "Startup": "4",
      "TotalFrames": "34",
      "Landing Lag": "",
      "Notes": "NA",
      "BaseDamage": "4.0",
      "Shieldlag": "11",
      "Shieldstun": "5",
      "<-Which hitbox?": "",
      "Advantage": "-25"
    },
    {
      "Moves": "F-Tilt ",
      "Startup": "8/9-10",
      "TotalFrames": "34",
      "Landing Lag": "",
      "Notes": "Breaks Often",
      "BaseDamage": "5.0 / 6.0",
      "Shieldlag": "11/6",
      "Shieldstun": "-/6",
      "<-Which hitbox?": "",
      "Advantage": "-19"
    },
    {
      "Moves": "U-Tilt",
      "Startup": "7-11",
      "TotalFrames": "35",
      "Landing Lag": "",
      "Notes": "Snake.jpg",
      "BaseDamage": "10.0",
      "Shieldlag": "8",
      "Shieldstun": "10",
      "<-Which hitbox?": "",
      "Advantage": "-18"
    },
    {
      "Moves": "D-Tilt",
      "Startup": "5-6",
      "TotalFrames": "27",
      "Landing Lag": "",
      "Notes": "N/A",
      "BaseDamage": "6.0",
      "Shieldlag": "6",
      "Shieldstun": "6",
      "<-Which hitbox?": "",
      "Advantage": "-16"
    },
    {
      "Moves": "Dash Attack",
      "Startup": "11-14/15-18",
      "TotalFrames": "37",
      "Landing Lag": "",
      "Notes": "Crosses up on shield",
      "BaseDamage": "11.0 / 8.0",
      "Shieldlag": "8/7",
      "Shieldstun": "10/8",
      "<-Which hitbox?": "Early/Late",
      "Advantage": "-16"
    },
    {
      "Moves": "F-Smash ",
      "Startup": "20-23",
      "TotalFrames": "41",
      "Landing Lag": "",
      "Notes": "Charge hold is frame 6",
      "BaseDamage": "15.0",
      "Shieldlag": "10",
      "Shieldstun": "10",
      "<-Which hitbox?": "",
      "Advantage": "-11 (SAFE AS HELL)"
    },
    {
      "Moves": "U-Smash",
      "Startup": "13-15/20-23",
      "TotalFrames": "47",
      "Landing Lag": "",
      "Notes": "DI 50/50, Best OOS Option",
      "BaseDamage": "6.0 / 12.0",
      "Shieldlag": "6/9",
      "Shieldstun": "5/8",
      "<-Which hitbox?": "",
      "Advantage": "-29/-19"
    },
    {
      "Moves": "D-Smash",
      "Startup": "14-15(Front) /21-22(Back)",
      "TotalFrames": "43",
      "Landing Lag": "",
      "Notes": "Ah gottem ggs",
      "BaseDamage": "14.0 (front close)/16.0(front tipper)\n12.0(back close)/14.0(back tipper)",
      "Shieldlag": "10 (front close)/10(front tipper)\n9(back close)/10(back tipper)",
      "Shieldstun": "10(front close)/11(front tipper)\n8(back close)/10(back tipper)",
      "<-Which hitbox?": "First close/far\nSecond close/far",
      "Advantage": "-19(front close)/-18(front tipper)\n-14(back close)/-12(back tipper)"
    },
    {
      "Moves": "N-Air",
      "Startup": "7-9(strong) / 10-26(Weak)",
      "TotalFrames": "42",
      "LandingLag": "9",
      "Notes": "Autocancels on frame 1-6 and 39 onward",
      "BaseDamage": "12.0(Strong) / 8.0(Weak)",
      "Shieldlag": "9/7",
      "Shieldstun": "5/4",
      "<-Which hitbox?": "Early/late",
      "Advantage": "-4(Strong)/-5(Weak)"
    },
    {
      "Moves": "F-Air",
      "Startup": "7-9",
      "TotalFrames": "40",
      "LandingLag": "10",
      "Notes": "Autocancels on frame 30 onward",
      "Base Damage": "9.0",
      "Shieldlag": "7",
      "Shieldstun": "4",
      "<-Which hitbox?": "",
      "Advantage": "-6"
    },
    {
      "Moves": "B-Air",
      "Startup": "13-15",
      "TotalFrames": "44",
      "LandingLag": "15",
      "Notes": "Autocancels on frame 1-7 and 19 onward",
      "BaseDamage": "15.0(Strong) / 11.0(Middle/Bulge)",
      "Shieldlag": "10/8",
      "Shieldstun": "5/4",
      "<-Which hitbox?": "Far/close",
      "Advantage": "-10(Strong) /-11(Middle/Bulge)"
    },
    {
      "Moves": "U-Air",
      "Startup": "7-9",
      "TotalFrames": "38",
      "LandingLag": "10",
      "Notes": "Autocancels on frame 1-3 and 31 onward",
      "BaseDamage": "12.0",
      "Shieldlag": "9",
      "Shieldstun": "5",
      "<-Which hitbox?": "",
      "Advantage": "-5"
    },
    {
      "Moves": "D-Air",
      "Startup": "16-17",
      "TotalFrames": "53",
      "LandingLag": "19",
      "Notes": "Autocancels on frame 1-4 and 36 onward",
      "BaseDamage": "15.0(Far) / 13.0(Close)",
      "Shieldlag": "10/9",
      "Shieldstun": "5/5",
      "<-Which hitbox?": "Far/close",
      "Advantage": "-14/-14"
    },
    {
      "Moves": "Blaster",
      "Startup": "15-19 (Bayonet)/ 16-50(Laser)",
      "TotalFrames": "52",
      "LandingLag": "",
      "Notes": "I now control neutral",
      "BaseDamage": "7.0(Bayonet) / 6.0(Shot)",
      "Shieldlag": "10/9",
      "Shieldstun": "-/3",
      "<-Which hitbox?": "",
      "Advantage": "-24"
    },
    {
      "Moves": "Wolf Flash",
      "Startup": "20-21",
      "TotalFrames": "N/A",
      "LandingLag": "29",
      "Notes": "Sweetspot is on frame 20. Can be slightly angled up or down",
      "BaseDamage": "15.0 (Sweet) / 3.0(Sour)",
      "Shieldlag": "18/5",
      "Shieldstun": "18/2",
      "<-Which hitbox?": "Sweet/sourspot",
      "Advantage": "lol"
    },
    {
      "Moves": "Fire Wolf",
      "Startup": "18/27/29/31/36",
      "TotalFrames": "66",
      "LandingLag": "36",
      "Notes": "Total frames refers to travel along the ground. Final hit does 1.0 more damage when you are airborne\nCan grab ledges as early as frame 27",
      "BaseDamage": "4.0 / 2.5 / 5.0",
      "Shieldlag": "5/5/15",
      "Shieldstun": "5/-/6",
      "<-Which hitbox?": "First/Multi/final",
      "Advantage": "-24"
    },
    {
      "Moves": "Reflector",
      "Startup": "6",
      "TotalFrames": "30",
      "LandingLag": "",
      "Notes": "Total frames refers to minimum usage. 12 endlag from extended usage. Invulnerable on frame 5-8. \nReflects as early as frame 9. A successful reflect lets you jump or dodge cancel out of the move",
      "BaseDamage": "4.0",
      "Shieldlag": "8",
      "Shieldstun": "5",
      "<-Which hitbox?": "",
      "Advantage": "-19"
    },
    {
      "Moves": "Grab",
      "Startup": "6",
      "Total Frames": "36",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Dash Grab ",
      "Startup": "8",
      "Total Frames": "44",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Pivot Grab",
      "Startup": "9",
      "Total Frames": "39",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Pummel",
      "Startup": "1",
      "Total Frames": "18",
      "Landing Lag": "",
      "Additional Notes": "Total frames includes 13 frames of hitlag (plus one in 1v1)",
      "Base Damage": "1.3",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Forward Throw",
      "Startup": "10/11",
      "Total Frames": "32",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "5.0 / 4.0",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Back Throw",
      "Startup": "23/24",
      "Total Frames": "47",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "6.0 / 5.0",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Up Throw",
      "Startup": "26/27",
      "Total Frames": "45",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "5.0 / 2.0",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Down Throw",
      "Startup": "26",
      "Total Frames": "40",
      "Landing Lag": "",
      "Additional Notes": "",
      "Base Damage": "8.5",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Spot Dodge",
      "Startup": "",
      "Total Frames": "20/25",
      "Landing Lag": "",
      "Additional Notes": "Invulnerable on frame 3-17",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Forward Roll",
      "Startup": "",
      "Total Frames": "29",
      "Landing Lag": "",
      "Additional Notes": "Invulnerable on frame 4-15",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Back Roll",
      "Startup": "",
      "Total Frames": "34",
      "Landing Lag": "",
      "Additional Notes": "Invulnerable on frame 5-16",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Neutral Air Dodge",
      "Startup": "",
      "Total Frames": "44",
      "Landing Lag": "10",
      "Additional Notes": "Invulnerable on frame 2-26",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Dir. AD (down)",
      "Startup": "",
      "Total Frames": "61",
      "Landing Lag": "11-19",
      "Additional Notes": "Invulnerable on frame 2-20",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Dir. AD (diagonally down)",
      "Startup": "",
      "Total Frames": "68",
      "Landing Lag": "11-19",
      "Additional Notes": "Invulnerable on frame 2-20",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Dir. AD (left or right)",
      "Startup": "",
      "Total Frames": "73",
      "Landing Lag": "11-19",
      "Additional Notes": "Invulnerable on frame 2-20",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Dir. AD (diagonally up)",
      "Startup": "",
      "Total Frames": "84",
      "Landing Lag": "11-19",
      "Additional Notes": "Invulnerable on frame 2-20",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    },
    {
      "Moves": "Dir. AD (up)",
      "Startup": "",
      "Total Frames": "93",
      "Landing Lag": "11-19",
      "Additional Notes": "Invulnerable on frame 2-20",
      "Base Damage": "",
      "Shieldlag": "",
      "Shieldstun": "",
      "<-Which hitbox?": "",
      "Advantage": ""
    }
  ]

  module.exports = wolfMoves
